############################
## Author
############################

author:
  name: Daniel Hosterman
  image: author.png
  greeting: "Hi!



  I'm Daniel Hosterman, 

  a software engineer, 

  gamer, 

  and photographer 

  living in Durham, NC."
  icon: ":wave:"

############################
## Links
############################

links:
  - email: mailto:daniel@danielhosterman.com
  # - github: https://github.com/dhosterman
  # - link: https://github.com/dhosterman/blog#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Daniel Hosterman
description: ""
images:
  - thumbnail.png
